services:
  - type: web
    name: otelcol
    region: frankfurt
    plan: starter
    runtime: docker
    buildFilter:
      paths:
      - otelcol/**/*
    dockerfilePath: ./otelcol/Dockerfile
    dockerContext: ./otelcol
    dockerCommand: /otelcol --config=/etc/otelcol/config.yaml
    envVars:
      - key: PORT
        value: 4318
      - key: OTEL_PROM_URL
        fromService:
          name: prometheus
          type: pserv
          property: hostport
