services:
  - type: web
    name: otelcol
    region: frankfurt
    plan: starter
    runtime: docker
    buildFilter:
      paths:
      - otelcol/**/*
    dockerfilePath: ./otelcol/Dockerfile
    dockerContext: ./otelcol
    dockerCommand: otelcol-contrib --config=/etc/otelcol/config.yaml
    envVars:
      - key: PORT
        value: 4318
      - fromGroup: datadog-apm
