services:
  - type: web
    name: otelcol
    region: frankfurt
    plan: starter
    runtime: docker
    buildFilter:
      paths:
      - otelcol/**/*
    dockerfilePath: ./otelcol/Dockerfile
    dockerContext: ./otelcol
    envVars:
      - key: PORT
        value: 4318
      - key: USERNAME
        value: otel
      - key: PASSWORD
        generateValue: true
      - fromGroup: datadog-apm
