receivers:
  otlp/basicauth:
    protocols:
      http:
        auth:
          authenticator: basicauth/server

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

exporters:
  datadog:
    api:
      site: datadoghq.eu
      key: ${env:DD_API_KEY}

service:
  extensions: [health_check, basicauth/server]
  telemetry:
    logs:
      level: WARN
  pipelines:
    traces:
      receivers: [otlp/basicauth]
      processors: [batch]
      exporters: [datadog]
    metrics:
      receivers: [otlp/basicauth]
      processors: [batch]
      exporters: [datadog]
    logs:
      receivers: [otlp/basicauth]
      processors: [batch]
      exporters: [datadog]

extensions:
  health_check:
  basicauth/server:
    htpasswd:
      inline: ${env:USERNAME}:${env:PASSWORD}
